# Generated by Django 5.2.1 on 2025-06-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Número da Placa')),
                ('is_regularized', models.BooleanField(default=True, verbose_name='Regularizada')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalhes Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placa Conhecida',
                'verbose_name_plural': 'Placas Conhecidas',
                'ordering': ['plate_number'],
            },
        ),
        migrations.RemoveField(
            model_name='detectedplate',
            name='plate_number',
        ),
        migrations.AddField(
            model_name='detectedplate',
            name='plate_number_detected',
            field=models.CharField(default='', max_length=20, verbose_name='Número da Placa Detectada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectedplate',
            name='known_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.knownplate', verbose_name='Placa Conhecida Associada'),
        ),
    ]
